// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Name = "IPhone 13",
                            Price = 50000m
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Name = "IPhone 14",
                            Price = 60000m
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            Name = "IPhone 15",
                            Price = 70000m
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Name = "IPhone 16",
                            Price = 80000m
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = true,
                            Name = "IPhone 17",
                            Price = 90000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
